#pragma once
// Add C includes here
#include "sqlite3.h"

#if defined __cplusplus
// Add C++ includes here
#include <SDKDDKVer.h>
#include <QPalette>
#include <QBrush>
#include <QColor>
#include "shobjidl_core.h"
#include <QSoundEffect>
#include <QFontDatabase>
#include <QApplication>
#include <chrono>
#include <iostream>
#include <QDebug>
#include <QHeaderView>
#include <QProcess>
#include <QMenu>
#include <QAction>
#include <QModelIndex>
#include <QPushButton>
#include <QScrollBar>
#include <QMimeDatabase>
#include <QMimeData>
#include <QMimeType>
#include <QTimer>
#include <QWindow>
#include <QScreen>
#include <QRect>
#include <QFileInfo>
#include <QMessageBox>
#include <QCryptographicHash>
#include <QDesktopServices>
#include <QMainWindow>
#include <QPoint>
#include <QTreeWidgetItem>
#include <QQueue>
#include "winuser.h"
#include "windef.h"
#include <QThread>
#include <QMutex>
#include <UIAutomationClient.h>
#include <QtGlobal>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlDriver>
#include <string>
#include <QTreeWidget>
#include <QList>
#include <QObject>
#include <QString>
#include <QUrl>
#include <QAudioDevice>
#include <QMediaFormat>
#include <QFile>
#include <QMediaPlayer>
#include <QAudioOutput>
#include <QPair>
#include <QPixmap>
#include <QDir>
#include <QtConcurrent>
#include <QFuture>
#include <windows.h>
#include <QCollator>
#include "libzippp/libzippp.h"
#include <QJsonDocument>
#include "timeapi.h"
#include <algorithm>
#include <cctype>
#include <math.h>
#include <QDirIterator>
#include "tlhelp32.h"
#include <map>
#include <iterator>
#include <mutex>
#include <condition_variable>
#include <stdlib.h>
#include <thread>
#include "ini.h"
#include <QEvent>
#include <QFrame>
#include <Qt>
#include <QLabel>
#include <QToolButton>
#include <QToolTip>
#include <QBoxLayout>
#include <QWidget>
#include <QStringList>
#include <QPainter>
#include <QGraphicsView>
#include <QGraphicsItem>
#include <QStyledItemDelegate>
#include <QAbstractItemView>
#include <QHelpEvent>
#include <QStyleOptionViewItem>
#include <QDialog>
#include <QMap>
#include <QSpinBox>
#include <QFileDialog>
#include <QCloseEvent>
#include <QSystemTrayIcon>
#include <QShortcut>
#include <QRegularExpression>
#include <QInputDialog>
#include <QImage>
#include <tuple>
#include <QPersistentModelIndex>
#include <QDateTime>
#include <QTime>
#include <QDate>
#include <QVariant>
#include <QJsonObject>
#include <QJsonArray>
#include <QJsonValue>
#include <QByteArray>
#include <QNetworkAccessManager>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QEventLoop>
#include <QLocalSocket>
#include <QRandomGenerator>
#include <QMediaDevices>
#include <QSet>
#include <QMutexLocker>
#include <QVariantMap>
#include <QTextStream>
#include <QDataStream>
#include <QIcon>
#include <QSize>
#include <QKeySequence>
#include <QProgressBar>
#include <QComboBox>
#include <QCheckBox>
#include <QLineEdit>
#include <QTextEdit>
#include <QGridLayout>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGroupBox>
#include <QTabWidget>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QSlider>
#include <QDoubleSpinBox>
#include <QFormLayout>
#include <QScrollArea>
#include <QSplitter>
#include <QStackedWidget>
#include <QButtonGroup>
#include <QRadioButton>
#include <QListWidget>
#include <QListWidgetItem>
#include <QDateTimeEdit>
#include <format>
#include <memory>
#include <functional>
#include <optional>
#include <deque>
#include <vector>
#include <QMetaType>
#include <QHash>
#include <QRgb>
#include <QBitArray>
#include <QStandardPaths>
#include <QCoreApplication>
#include <QSettings>
#include <QToolBar>
#include <QMenuBar>
#include <QStatusBar>
#include <QSizePolicy>
#include <QMovie>
#include <QGraphicsScene>
#include <QGraphicsPixmapItem>
#include <QGraphicsProxyWidget>
#include <QPropertyAnimation>
#include <QEasingCurve>
#include <QParallelAnimationGroup>
#include <QSequentialAnimationGroup>
#include <QGraphicsOpacityEffect>
#include <QGraphicsColorizeEffect>
#include <QGraphicsBlurEffect>
#include <QGraphicsDropShadowEffect>
#include <QResizeEvent>
#include <QMouseEvent>
#include <QKeyEvent>
#include <QWheelEvent>
#include <QPaintEvent>
#include <QShowEvent>
#include <QHideEvent>
#include <QMoveEvent>
#include <QFocusEvent>
#include <QEnterEvent>
#include <QContextMenuEvent>
#include <QDragEnterEvent>
#include <QDragMoveEvent>
#include <QDragLeaveEvent>
#include <QDropEvent>
#include <QTimerEvent>
#include <QChildEvent>
#endif
