#pragma once
// Add C includes here
#include "sqlite3.h"

#if defined __cplusplus
// Add C++ includes here
#include <SDKDDKVer.h>
#include <QPalette>
#include <QBrush>
#include <QColor>
#include "shobjidl_core.h"
#include <QSoundEffect>
#include <QFontDatabase>
#include <QApplication>
#include <chrono>
#include <iostream>
#include <QDebug>
#include <QHeaderView>
#include <QProcess>
#include <QMenu>
#include <QAction>
#include <QModelIndex>
#include <QPushButton>
#include <QScrollBar>
#include <QMimeDatabase>
#include <QMimeData>
#include <QMimeType>
#include <QTimer>
#include <QWindow>
#include <QScreen>
#include <QRect>
#include <QFileInfo>
#include <QMessageBox>
#include <QCryptographicHash>
#include <QDesktopServices>
#include <QMainWindow>
#include <QPoint>
#include <QTreeWidgetItem>
#include <QQueue>
#include "winuser.h"
#include "windef.h"
#include <QThread>
#include <QMutex>
#include <UIAutomationClient.h>
#include <QtGlobal>
#include <QSqlDatabase>
#include <QSqlQuery>
#include <QSqlError>
#include <QSqlDriver>
#include <string>
#include <QTreeWidget>
#include <QList>
#include <QObject>
#include <QString>
#include <QUrl>
#include <QAudioDevice>
#include <QMediaFormat>
#include <QFile>
#include <QMediaPlayer>
#include <QAudioOutput>
#include <QPair>
#include <QPixmap>
#include <QDir>
#include <QtConcurrent>
#include <QFuture>
#include <windows.h>
#include <QCollator>
#include "libzippp/libzippp.h"
#include <QJsonDocument>
#include "timeapi.h"
#include <algorithm>
#include <cctype>
#include <math.h>
#include <QDirIterator>
#include "tlhelp32.h"
#include <map>
#include <iterator>
#include <mutex>
#include <condition_variable>
#include <stdlib.h>
#include <thread>
#include "ini.h"
#include <QEvent>
#include <QFrame>
#include <Qt>
#include <QLabel>
#include <QToolButton>
#include <QToolTip>
#include <QBoxLayout>
#include <QWidget>
#include <QStringList>
#include <QPainter>
#include <QGraphicsView>
#include <QGraphicsItem>
#include <QStyledItemDelegate>
#include <QAbstractItemView>
#include <QHelpEvent>
#include <QStyleOptionViewItem>
#include <QDialog>
#include <QMap>
#include <QSpinBox>
#include <QFileDialog>
#include <QCloseEvent>
#include <QSystemTrayIcon>
#include <QShortcut>
#include <QRegularExpression>
#include <QInputDialog>
#include <QImage>
#include <tuple>
#include <QPersistentModelIndex>
#endif
